homeassistant:
  enabled: true
  legacy_action_sensor: true
  discovery_topic: homeassistant
mqtt:
  server: mqtt://a0d7b954-emqx:1883
  keepalive: 60
  password: oquohchaijeibaiMohngaveepei6OP1hohhohm3oaj0oquaethaakaafiotohy5t
  reject_unauthorized: true
  user: z2muser
  version: 5
  include_device_information: true
  client_id: z2m-main-cc2652p
  maximum_packet_size: 268435456
serial:
  adapter: zstack
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0af6c3286645ed11b163cf8f0a86e0b4-if00-port0
  baudrate: 115200
  rtscts: false
frontend:
  enabled: true
  package: zigbee2mqtt-windfront
  port: 8099
advanced:
  pan_id: 8367
  ext_pan_id:
    - 122
    - 195
    - 145
    - 78
    - 184
    - 45
    - 246
    - 9
  network_key: '!secret.yaml network_key'
  channel: 25
  log_level: warning
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  adapter_concurrent: 12
  last_seen: ISO_8601_local
  transmit_power: 5
  output: json
  disable_device_removal: true
device_options:
  retain: false
availability:
  enabled: true
  active:
    timeout: 90
  passive:
    timeout: 1500
devices:
  '0xec1bbdfffe41a041':
    friendly_name: Owner Suite/Lamp Bulb 1
    description: ''
  '0xccccccfffe2d6ab9':
    friendly_name: Owner Suite/Lamp Bulb 2
    description: ''
  '0x24fd5b0001053807':
    friendly_name: Arrival Sensor
    description: Car presence detection
    legacy: false
  '0x00158d0001e574f5':
    friendly_name: Hall/Main Foyer/Motion
  '0x001788010960e819':
    friendly_name: Basement/North Hallway 2
  '0x001788010960e758':
    friendly_name: Basement/North Hallway 1
  '0x001788010b3e30a8':
    friendly_name: Basement/Landing 1
  '0x001788010b3e3aa6':
    friendly_name: Basement/Landing 2
  '0x001788010b3dc793':
    friendly_name: Basement/Great Room West 1
  '0x001788010b3e30fe':
    friendly_name: Basement/Great Room West 2
  '0x001788010b3dc70f':
    friendly_name: Basement/Great Room West 3
  '0x001788010b3e30d5':
    friendly_name: Basement/Great Room Middle 1
  '0x001788010b3e31e2':
    friendly_name: Basement/Great East Room 2
  '0x001788010b3e30ad':
    friendly_name: Basement/Great Room East 1
  '0x001788010b3e178e':
    friendly_name: Basement/Great Room Middle 2
  '0x00158d0006e16b54':
    friendly_name: Hall/Main Foyer 1
  '0x00158d0006e168df':
    friendly_name: Hall/Main Foyer 2
  '0x00158d0007c9da38':
    friendly_name: Hall/Upstairs 2
  '0x00158d0006e16ba2':
    friendly_name: Owner Suite/Bathroom/Shower
  '0x00158d0006dc0246':
    friendly_name: Hall/Upstairs 1
  '0x00158d0006e16b29':
    friendly_name: Basement/Bathroom Shower
  '0x00158d0006f940d1':
    friendly_name: Kitchen/Sink Leak
  '0x00178801060acba3':
    friendly_name: Den/Flood 1
  '0x00178801060acb6c':
    friendly_name: Den/Flood 2
  '0x00158d0006f815dc':
    friendly_name: Kitchen/Dishwasher Leak
  '0x00158d0007d39b7d':
    friendly_name: Basement/Closet TPH
  '0x5c0272fffe6c6afd':
    friendly_name: Owner Suite/Blind Control
  '0x588e81fffe0596f5':
    friendly_name: Deck/String
    homeassistant:
      switch:
        type: light
        object_id: light
      light:
        state_value_template: '{{ value_json.state }}'
  '0x00158d00022883cc':
    friendly_name: Guest Room/TPH
  '0x00158d0002272e17':
    friendly_name: Owner Suite/Bathroom/TPH
  '0x00158d000223a007':
    friendly_name: Owner Suite/TPH
  '0x00158d0001e57378':
    friendly_name: Office/Motion
    occupancy_timeout: 300
  '0x00158d0002c8f3c1':
    friendly_name: Office/TPH
  '0x00158d00028f6612':
    friendly_name: Owner Suite/Cube
    legacy: false
    device_temperature_precision: 0
  '0x00158d0001e5227d':
    friendly_name: Basement/Landing
  '0x00158d0001e523fe':
    friendly_name: Owner Suite/Bathroom/Room
  '0xd0cf5efffe7ccba7':
    friendly_name: Tiki Room/Camera
  '0xd0cf5efffeda9959':
    friendly_name: Garage/Plug
  '0x00158d0007e39eb5':
    friendly_name: '0x00158d0007e39eb5'
  '0x00158d0007e39b62':
    friendly_name: '0x00158d0007e39b62'
  '0x00158d0007efa769':
    friendly_name: Hall/Upstairs/Motion
  '0x00178801104ec673':
    friendly_name: Dining Room/Lamp 1
  '0x001788011037fb63':
    friendly_name: Dining Room/Lamp 2
  '0x00158d0001f2a70a':
    friendly_name: Hall/Button
  '0x00158d0006ea4e10':
    friendly_name: Laundry/Leak
  '0x001788010c363edf':
    friendly_name: Office/Floor Lamp 2
  '0xb0ce1814036bbbf9':
    friendly_name: Owner Suite/CPAP Plug
  '0xb0ce1814036bad3c':
    friendly_name: Basement/Sump Pump
  '0x00158d00080ce4fc':
    friendly_name: Kitchen/Deck
  '0x00158d00080ceb09':
    friendly_name: Den/Doors
  '0x00158d00080cd74c':
    friendly_name: Tiki Room/Deck
  '0x00158d0008104588':
    friendly_name: Main Foyer/Front Door
  '0x00158d00081048e4':
    friendly_name: Hall/Garage Entry
  '0x00178801104eaee4':
    friendly_name: Tiki Room/Floor Lamp
  '0x00158d00029133e5':
    friendly_name: Doorbell
  '0x00158d0002c8d19b':
    friendly_name: Tiki Room/TPH
  '0x001788010bf71353':
    friendly_name: Basement/Stair Landing
  '0x001788010bf71029':
    friendly_name: Hall/Transition
  '0x001788010bf7124d':
    friendly_name: Hall/Laundry
  '0x00158d0007efc889':
    friendly_name: Kitchen/Motion
  '0x000d6f0005937456':
    friendly_name: Tiki Room/Heater
  '0x94deb8fffef4c02c':
    friendly_name: Guest Room/Fan Switch
  '0x040d84fffe02ba25':
    friendly_name: Den/Wall Switch
  '0x943469fffe088e56':
    friendly_name: Basement/Great Room East and Middle Switch
  '0x385b44fffeee1c4d':
    friendly_name: Dining Room/Overhead
  '0x001788010bfa347e':
    friendly_name: Dining Room/Overhead 2
  '0x001788010bfa278c':
    friendly_name: Dining Room/Overhead 4
  '0x001788010bfa0a25':
    friendly_name: Dining Room/Overhead 1
  '0x001788010bfa3295':
    friendly_name: Dining Room/Overhead 3
  '0x385b44fffee8eafb':
    friendly_name: Hall/Foyer Switch
    description: Located in living room
  '0x842e14fffe757a4a':
    friendly_name: Owner Suite/North Blind
  '0x842e14fffe5afb9d':
    friendly_name: Owner Suite/South Blind
  '0xb4e3f9fffe8e441d':
    friendly_name: Office/Light Button 1
  '0x94deb8fffe459159':
    friendly_name: Owner Suite/Closet
  '0x70ac08fffe7350fd':
    friendly_name: Dining Room/Wall Switch
  '0xe0798dfffed2cd60':
    friendly_name: Owner Suite/Bathroom/Vanity
  '0xe0798dfffed2d17f':
    friendly_name: Hall/Stairway
  '0x943469fffe05d25a':
    friendly_name: Kitchen/Overhead Lights Switch
  '0x70ac08fffe7353a5':
    friendly_name: Hall/Transition Switch
  '0x943469fffe0895fb':
    friendly_name: Kitchen/Under Cabinet
  '0x94deb8fffe45920d':
    friendly_name: Basement/Landing Switch
  '0x943469fffe05d064':
    friendly_name: Garage/Overhead Switch
  '0xe0798dfffed2c840':
    friendly_name: Owner Suite/Bathroom/Shower Switch
  '0x943469fffe089dd4':
    friendly_name: Basement/Bathroom/Shower Switch
  '0x94deb8fffe4c0f5b':
    friendly_name: Hall/Upstairs/Switch
  '0x70ac08fffe734ad3':
    friendly_name: Deck/Kitchen Door
  '0x385b44fffeee10ff':
    friendly_name: Deck/Flood Lights
  '0x70ac08fffe710e05':
    friendly_name: Basement/Overhead Outlet
  '0x040d84fffe05f823':
    friendly_name: Basement/Great Room West Switch
  '0x943469fffe089a5b':
    friendly_name: Basement/North Hallway Switch
  '0x943469fffe05d486':
    friendly_name: Laundry/Wall Switch
  '0x000d6f0004a86086':
    friendly_name: Laundry/Outlet Repeater
  '0x540f57fffe3eb3f0':
    friendly_name: Den/Sonos Controls
  '0x00158d0002b31529':
    friendly_name: Laundry/Washer Vibration
  '0x001788010c65dfef':
    friendly_name: Outside/South West Garage
  '0x001788010c65dfe8':
    friendly_name: Outside/North West Garage
  '0x001788010be7e25f':
    friendly_name: Outside/Front Door
  '0x001788010d21a619':
    friendly_name: Garage/Back Door
  '0x001788010d16e2fc':
    friendly_name: Deck/Kitchen Door Light
  '0x001788010d219d65':
    friendly_name: Deck/Tiki Room Door
  '0x040d84fffe05fbc7':
    friendly_name: Basement/Great Room Landing Switch 2
  '0x2c1165fffebe96fd':
    friendly_name: Office/Red Lava Lamp
  '0x048727fffe1bf44f':
    friendly_name: Owner Suite/Bathroom/Exhaust
  '0x040d84fffe05f409':
    friendly_name: Owner Suite/Fan Switch
  '0x048727fffe1c0caa':
    friendly_name: Basement/Bathroom/Exhaust
  '0x048727fffe1bd2a6':
    friendly_name: Guest Bathroom/Exhaust
  '0x00158d0002c8f389':
    friendly_name: Basement/Bathroom/TPH
  '0x00158d0007c0d6ce':
    friendly_name: Guest Bathroom/TPH
  '0x943469fffe05ca33':
    friendly_name: Office/Fan Switch
  '0xec1bbdfffe8a6c1b':
    friendly_name: Den/Leather Chair
  '0x943469fffe05d234':
    friendly_name: Owner Suite/Bathroom/Tub Switch
  '0x000d6f000549b3b5':
    friendly_name: '0x000d6f000549b3b5'
  '0xb4e3f9fffe8dde4a':
    friendly_name: Office/Light Button 2
  '0xa4c138bd80f16e1e':
    friendly_name: Basement/Water Shutoff
  '0x5cc7c1fffe88a2e4':
    friendly_name: '0x5cc7c1fffe88a2e4'
  '0x6c5cb1fffe080a56':
    friendly_name: East Bed Button
  '0x385b44fffee8eb06':
    friendly_name: Kitchen/Kitchen Sink
    description: Front Door Interior Entry (switch in dining/living area)
  '0x048727fffe52124b':
    friendly_name: Mailbox
  '0x00158d0007e0d8fc':
    friendly_name: Basement/TPH
  '0x00158d0001f378cc':
    friendly_name: '0x00158d0001f378cc'
  '0x6c5cb1fffe0800aa':
    friendly_name: West Bed Button
  '0x001788010e9eba9a':
    friendly_name: Kitchen/Overhead 3
  '0x001788010ebd96c8':
    friendly_name: Kitchen/Overhead 6
  '0x001788010e9ea0bb':
    friendly_name: Kitchen/Overhead 5
  '0x001788010ebd8caf':
    friendly_name: Kitchen/Overhead 1
  '0x001788010ebd8c8d':
    friendly_name: Kitchen/Overhead 7
  '0x001788010ebd90ab':
    friendly_name: Kitchen/Overhead 2
  '0x001788010ebd901d':
    friendly_name: Kitchen/Overhead 4
  '0x001788010ebd8cfb':
    friendly_name: Kitchen/Sink Overhead
  '0x943469fffe08991b':
    friendly_name: Hall/Garage Laundry Switch
  '0x00158d00070150d1':
    friendly_name: Basement/Unfinished Leak
  '0x001788010c366771':
    friendly_name: Office/Floor Lamp 1
  '0x94deb8fffef4d847':
    friendly_name: Outside/Front Lights
  '0x001788010bfa082a':
    friendly_name: Kitchen/Bay Light
  '0x9035eafffeec5f5e':
    friendly_name: Tiki Room/Sonos Control
  '0x00158d0007d3c452':
    friendly_name: Hall/Upstairs/Linen Closet/TPH
  '0x385b44fffeee10c8':
    friendly_name: Kitchen/Sink Overhead Switch
  '0x00158d0006e0cff4':
    friendly_name: '0x00158d0006e0cff4'
groups:
  '1':
    friendly_name: Owner Suite/Lamps
  '2':
    friendly_name: Hall/All
  '3':
    friendly_name: Office/Floor Lamp
  '4':
    friendly_name: Basement/Great Room
  '5':
    friendly_name: Dining Room/All
  '6':
    friendly_name: Dining Room/Lamps
  '7':
    friendly_name: Den/Floods
  '10':
    friendly_name: Deck/All
  '11':
    friendly_name: Deck/Hue
  '12':
    friendly_name: Den/All
  '14':
    friendly_name: Dining Room/Over Table
  '17':
    friendly_name: Living Room/Lamps
  '19':
    friendly_name: Outside/Front Hue
  '22':
    friendly_name: Owner Suite/Bathroom/Lights
  '25':
    friendly_name: Kitchen/All
version: 5
